backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Short description', name: 'description', widget: 'text' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'To add an image use Rich Text image selector',
        }
      - {
          label: 'Tag',
          name: 'tags',
          hint: 'A comma separated list of tags',
          widget: 'list',
        }
